version: "2"
services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  app:
    container_name: app
    restart: always
    build: .
    volumes:
      - ./app:/usr/src/db-live/app
      - ./node_modules:/usr/src/db-live/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    links:
      - mongo