version: "2"
services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  sofy:
    container_name: sofy
    command: ["yarn", "start:dev"]
    restart: always
    build: .
    volumes:
      - ./app:/usr/src/sofy/app
      - ./node_modules:/usr/src/sofy/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    links:
      - mongo